import fs from 'fs';
import path from 'path';
import os from 'os';
import {
  buildLeadSubagentView,
  findNativeSessionFile,
  parseNativeSession
} from '../visualizer/lead-subagent-trace.js';
import {
  cleanText,
  contentToText,
  summarizeDoes,
  summarizeContext,
  summarizeOutcome,
  summarizeStatus
} from './summary.js';
import { writeTraceMarkdown } from './markdown-export.js';

const APP_HOME = process.env.CLAUDE_CODE_LENS_HOME ||
  path.join(os.homedir(), '.claude-code-lens');
export const DEFAULT_LOG_DIR = path.join(APP_HOME, 'raw_logs');
export const DEFAULT_PROJECTS_DIR = process.env.CLAUDE_CODE_LENS_CLAUDE_PROJECTS_DIR ||
  path.join(os.homedir(), '.claude', 'projects');

export class TraceError extends Error {
  constructor(code, message, hint, exitCode = 1) {
    super(message);
    this.name = 'TraceError';
    this.code = code;
    this.hint = hint;
    this.exitCode = exitCode;
  }
}

function safeJsonParse(text) {
  try {
    return JSON.parse(text);
  } catch {
    return null;
  }
}

async function readJson(filePath) {
  return JSON.parse(await fs.promises.readFile(filePath, 'utf8'));
}

function readJsonl(filePath) {
  try {
    return fs.readFileSync(filePath, 'utf8')
      .split('\n')
      .map(line => line.trim())
      .filter(Boolean)
      .map(safeJsonParse)
      .filter(Boolean);
  } catch {
    return [];
  }
}

function isLogFileName(name) {
  return name.endsWith('.json') && (name.startsWith('messages-') || name === 'messages-test.json');
}

export async function findLogFiles(logDir = DEFAULT_LOG_DIR) {
  let entries = [];
  try {
    entries = await fs.promises.readdir(logDir, { withFileTypes: true });
  } catch {
    return [];
  }

  const files = await Promise.all(entries
    .filter(entry => entry.isFile() && isLogFileName(entry.name))
    .map(async entry => {
      const filePath = path.join(logDir, entry.name);
      const stat = await fs.promises.stat(filePath);
      return { filePath, mtime: stat.mtimeMs };
    }));

  return files.sort((a, b) => b.mtime - a.mtime).map(file => file.filePath);
}

function blockToolUses(content, names = ['Agent', 'Task']) {
  if (!Array.isArray(content)) return [];
  return content.filter(block => block?.type === 'tool_use' && names.includes(block.name));
}

function collectSpawnDetails(nativeFile) {
  const events = readJsonl(nativeFile);
  const spawns = [];

  events.forEach((event, index) => {
    if (event.type !== 'assistant') return;
    for (const block of blockToolUses(event.message?.content)) {
      const resultEvent = events.slice(index + 1).find(candidate =>
        candidate.type === 'user' &&
        Array.isArray(candidate.message?.content) &&
        candidate.message.content.some(item => item?.type === 'tool_result' && item.tool_use_id === block.id)
      );
      const resultBlock = resultEvent?.message?.content?.find(item =>
        item?.type === 'tool_result' && item.tool_use_id === block.id
      );
      spawns.push({
        id: block.id,
        timestamp: event.timestamp,
        description: cleanText(block.input?.description || ''),
        subagentType: cleanText(block.input?.subagent_type || ''),
        prompt: cleanText(block.input?.prompt || ''),
        result: cleanText(contentToText(resultBlock?.content))
      });
    }
  });

  return spawns;
}

function matchSpawn(agent, spawns) {
  return spawns.find(spawn =>
    spawn.timestamp === agent.spawnTimestamp &&
    (!agent.subagentType || spawn.subagentType === agent.subagentType) &&
    (!agent.description || spawn.description === agent.description)
  ) || null;
}

function meaningfulNativeText(events, { fromEnd = false } = {}) {
  const source = fromEnd ? [...events].reverse() : events;
  for (const event of source) {
    if (event.type !== 'user' && event.type !== 'assistant') continue;
    const text = cleanText(contentToText(event.message?.content));
    if (!text) continue;
    if (/^count$/i.test(text)) continue;
    if (/Caveat: The messages below were generated by the user while running local commands/i.test(text)) continue;
    return text;
  }
  return '';
}

function firstModelThinking(logData) {
  const outputs = (logData?.interactions || [])
    .filter(interaction => ['output', 'stream.final'].includes(interaction?.type))
    .sort((a, b) => Date.parse(a.timestamp || 0) - Date.parse(b.timestamp || 0));
  for (const output of outputs) {
    for (const block of output.data?.content || []) {
      if (block?.type !== 'thinking') continue;
      const thinking = cleanText(block.thinking || '');
      if (thinking) return thinking;
    }
  }
  return '';
}

function summarizeAgent(agent, { spawn = null, events = [], maxPreview, debug = false } = {}) {
  const isLead = agent.role === 'lead';
  const doesSource = isLead
    ? (meaningfulNativeText(events) || agent.firstUserText || agent.description || agent.name)
    : (spawn?.prompt || agent.firstUserText || agent.description || agent.name);
  const outcomeSource = isLead
    ? meaningfulNativeText(events, { fromEnd: true })
    : (spawn?.result || agent.firstText || meaningfulNativeText(events, { fromEnd: true }));
  const summary = {
    id: agent.id,
    role: agent.role,
    name: agent.name,
    does: summarizeDoes(doesSource, maxPreview),
    outcome: summarizeOutcome(outcomeSource, maxPreview)
  };
  if (debug) {
    summary.debug = {
      requestCount: agent.requestCount || 0,
      eventCount: agent.eventCount,
      toolsUsed: agent.toolsUsed || {},
      source: {
        doesFrom: isLead ? 'lead.firstMeaningfulText' : (spawn?.prompt ? 'Agent.input.prompt' : 'subagent.firstUserText'),
        outcomeFrom: isLead ? 'lead.lastMeaningfulText' : (spawn?.result ? 'Agent.tool_result.content' : 'subagent.lastMeaningfulText')
      }
    };
  }
  return summary;
}

function requestCounts(assignments) {
  const counts = {};
  for (const assignment of Object.values(assignments || {})) {
    counts[assignment.agentId] = (counts[assignment.agentId] || 0) + 1;
  }
  return counts;
}

function nativeEventsByAgent(nativeTrace) {
  const result = new Map();
  if (!nativeTrace?.nativeFile) return result;
  result.set('lead', readJsonl(nativeTrace.nativeFile));
  for (const agent of nativeTrace.agents || []) {
    if (agent.role !== 'subagent' || !agent.sourceFile) continue;
    result.set(agent.id, readJsonl(agent.sourceFile));
  }
  return result;
}

async function buildSessionContext(logFile, options = {}) {
  const logData = await readJson(logFile);
  if (!logData?.session_id) {
    throw new TraceError('INVALID_LOG', `Log file has no session_id: ${logFile}`);
  }

  const view = await buildLeadSubagentView(logData, {
    projectsDir: options.projectsDir || DEFAULT_PROJECTS_DIR
  });
  const nativeFile = view.nativeTrace?.found
    ? view.nativeTrace.nativeFile
    : await findNativeSessionFile(logData.session_id, options.projectsDir || DEFAULT_PROJECTS_DIR);
  const nativeTrace = nativeFile ? parseNativeSession(nativeFile) : null;
  const spawns = nativeFile ? collectSpawnDetails(nativeFile) : [];
  const counts = requestCounts(view.assignments);
  const eventsByAgent = nativeTrace ? nativeEventsByAgent(nativeTrace) : new Map();
  const agents = (nativeTrace?.agents || view.agents || []).map(agent => ({
    ...agent,
    requestCount: counts[agent.id] || 0
  }));

  const leadEvents = eventsByAgent.get('lead') || [];
  const contextSource = firstModelThinking(logData) ||
    meaningfulNativeText(leadEvents) ||
    agents.find(agent => agent.role === 'subagent')?.firstUserText ||
    logData.session_id;
  const statusSource = meaningfulNativeText(leadEvents, { fromEnd: true }) || contextSource;
  const subagentCount = agents.filter(agent => agent.role === 'subagent').length;

  return {
    logFile,
    logData,
    view,
    nativeTrace,
    spawns,
    eventsByAgent,
    summary: {
      sessionId: logData.session_id,
      startedAt: logData.created_at || leadEvents[0]?.timestamp || null,
      context: summarizeContext(contextSource, options.maxPreview),
      status: summarizeStatus(statusSource, options.maxPreview),
      agents: `lead + ${subagentCount} subagents`
    },
    agents
  };
}

function matchesQuery(session, query) {
  if (!query) return true;
  const needle = query.toLowerCase();
  const haystack = [
    session.summary.sessionId,
    session.summary.context,
    session.summary.status,
    session.summary.agents,
    ...session.agents.map(agent => agent.name)
  ].join(' ').toLowerCase();
  return haystack.includes(needle);
}

export async function listTraceSessions(options = {}) {
  const files = await findLogFiles(options.logDir || DEFAULT_LOG_DIR);
  if (!files.length) {
    throw new TraceError('NO_LOGS', 'No Claude Code Lens raw logs found', 'Run cclens first to capture a Claude Code session.', 66);
  }

  const sessions = [];
  for (const file of files) {
    if (options.limit && sessions.length >= options.limit) break;
    try {
      const context = await buildSessionContext(file, options);
      if (options.since && context.summary.startedAt && Date.parse(context.summary.startedAt) < Date.parse(options.since)) {
        continue;
      }
      if (!matchesQuery(context, options.query)) continue;
      const summary = { ...context.summary };
      if (options.debug) {
        summary.debug = {
          logFile: context.logFile,
          nativeFile: context.view.nativeTrace?.nativeFile || null,
          attribution: context.view.stats
        };
      }
      sessions.push(summary);
    } catch (error) {
      if (options.debug) {
        sessions.push({
          sessionId: null,
          startedAt: null,
          context: '',
          status: '',
          agents: 'lead + 0 subagents',
          debug: { logFile: file, error: error.message }
        });
      }
    }
  }

  return { sessions };
}

async function findSessionContext(sessionId, options = {}) {
  const files = await findLogFiles(options.logDir || DEFAULT_LOG_DIR);
  for (const file of files) {
    const logData = await readJson(file);
    if (logData?.session_id === sessionId) {
      return buildSessionContext(file, options);
    }
  }
  throw new TraceError(
    'SESSION_NOT_FOUND',
    `No trace session found for ${sessionId}`,
    'Run cclens trace list -f json and choose one of sessions[].sessionId',
    66
  );
}

export async function showTraceSession(sessionId, options = {}) {
  const context = await findSessionContext(sessionId, options);
  const agents = context.agents.map(agent => summarizeAgent(agent, {
    spawn: matchSpawn(agent, context.spawns),
    events: context.eventsByAgent.get(agent.id) || [],
    maxPreview: options.maxPreview,
    debug: options.debug
  }));

  const result = {
    ...context.summary,
    agents
  };
  if (options.debug) {
    result.debug = {
      logFile: context.logFile,
      nativeFile: context.view.nativeTrace?.nativeFile || null,
      attribution: context.view.stats
    };
  }
  return result;
}

export async function exportTraceSession(sessionId, agentId, options = {}) {
  const context = await findSessionContext(sessionId, options);
  const shown = await showTraceSession(sessionId, options);
  const agent = shown.agents.find(item => item.id === agentId) ||
    (agentId === 'all' ? { id: 'all', role: 'all', name: 'All agents' } : null);
  if (!agent) {
    throw new TraceError(
      'AGENT_NOT_FOUND',
      `No agent ${agentId} found in session ${sessionId}`,
      'Run cclens trace show --session <sessionId> -f json and choose one of agents[].id',
      66
    );
  }

  try {
    const markdownPath = await writeTraceMarkdown({
      logData: context.logData,
      assignments: context.view.assignments,
      agentId,
      leadSubagentView: context.view,
      outPath: options.out
    });
    return {
      markdownPath,
      sessionId,
      agent
    };
  } catch (error) {
    throw new TraceError('EXPORT_FAILED', error.message, 'Check the output path and file permissions.');
  }
}
